/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileDescriptor;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Domain.*;
import GUI.opciones.Op1;
import GUI.opciones.Op10;
import GUI.opciones.Op2;
import GUI.opciones.Op3;
import GUI.opciones.Op4;
import GUI.opciones.Op404;
import GUI.opciones.Op5;
import GUI.opciones.Op6;
import GUI.opciones.Op7;
import GUI.opciones.Op8;
import GUI.opciones.Op9;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.Timer;

public final class Menu extends javax.swing.JFrame {

    String address = "";
    EnsambladorDeFragmentosPrueba ensamblador;
    private int index = 0;
    // boolean[] check = {false, false, false, false};
    boolean[] check = {true, true, true, true};

    public Menu() {
        ensamblador = new EnsambladorDeFragmentosPrueba();
        super.setUndecorated(false);
        initComponents();
        super.setLocationRelativeTo(null);
        super.setResizable(false);
        derechos();
        this.setVisible(true);
        String palabra = "Se debe respetar el orden de las opciones o tendras problemas, una ves ejecutado la opcion 1,\n"
                + "la opcion dos se desbloqueara y asi susesivamente.\n"
                + "si vas por las opcion 3 y te devuelves a la opcion 1, no tendras ningun problema.\n"
                + "el orden de las  Opciones es:\n"
                + "1. Cargar fragmentos\n"
                + "2. Fragmentos aleatorios\n"
                + "3. Crear matriz de traslapes\n"
                + "4. Ensamblar fragmentos\n"
                + "Si ya el archivo esta fragmentado, no hay necesidad de hacer el paso 2. Fragmentos aleatorios";
        String palabraLabel = "El proyecto consiste en desarrollar un programa que reconstruye un texto original a partir de fragmentos de texto, utilizando una aproximación al algoritmo de Superhilera Mínima Común.";
        iniciar(palabra, palabraLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlabelDerechos1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        titu1 = new javax.swing.JLabel();
        titu3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        titu2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlabelDerechos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        titu8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelDerechos1.setBackground(new java.awt.Color(255, 255, 255));
        jlabelDerechos1.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jlabelDerechos1.setForeground(new java.awt.Color(0, 0, 0));
        jlabelDerechos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelDerechos1.setText("Antony Monge, Anthonio Alvarez");
        jPanel2.add(jlabelDerechos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 190, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 102)));
        jPanel5.setForeground(new java.awt.Color(153, 0, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu1.setBackground(new java.awt.Color(0, 102, 102));
        titu1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        titu1.setForeground(new java.awt.Color(0, 0, 0));
        titu1.setText("Ensamblaje");
        jPanel5.add(titu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, -1));

        titu3.setBackground(new java.awt.Color(0, 102, 102));
        titu3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        titu3.setForeground(new java.awt.Color(0, 0, 0));
        titu3.setText("de Fragmentos");
        jPanel5.add(titu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 60));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Opciones", "1. Cargar fragmentos", "2. Fragmentos aleatorios", "3. Crear matriz de traslapes", "4. Ensamblar fragmentos", "5. Guardar ensamblado en archivo", "6. Calcular similitud con hilera original", "7. Listar fragmentos", "8. Ordenar alfabéticamente", "9. Filtrar fragmentos por longitud", "10. Buscar fragmentos por palabra clave", "11. Generar grafo conexo mínimo" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 40));

        titu2.setBackground(new java.awt.Color(0, 102, 102));
        titu2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titu2.setForeground(new java.awt.Color(0, 0, 0));
        titu2.setText("Menu");
        jPanel2.add(titu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jlabelDerechos.setBackground(new java.awt.Color(255, 255, 255));
        jlabelDerechos.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jlabelDerechos.setForeground(new java.awt.Color(255, 255, 255));
        jlabelDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jlabelDerechos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelDerechos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 220, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 230, 600));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 36));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 60));

        jPanel_Menu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Menu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_Menu.setLayout(new java.awt.BorderLayout());

        titu8.setBackground(new java.awt.Color(255, 0, 0));
        titu8.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 100)); // NOI18N
        titu8.setForeground(new java.awt.Color(0, 0, 0));
        titu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu8.setText("Instrucciones");
        titu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Menu.add(titu8, java.awt.BorderLayout.CENTER);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel_Menu.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:Opciones
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        opcionesMenuListaSimple();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void opcionesMenuListaSimple() {
        try (Scanner scanner = new Scanner(System.in)) {
            System.err.println("Tamano:"+ensamblador.getTamano()); 
            
            System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out), true, "UTF-8"));
            if (jComboBox1.getSelectedIndex() == 1) {
                System.out.println("Se seleccionó la opción 1");
                FileGetAddress f = new FileGetAddress();
                address = f.fileAddress();

                if (!address.equalsIgnoreCase("404")) {
                    check[0] = true;
                    ensamblador.cargarFragmentosDeArchivo(address);
                    Op1 oP = new Op1();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }
            //////////////
            if (jComboBox1.getSelectedIndex() == 2) {
                System.out.println("Se seleccionó la opción 2");

                if (!address.equalsIgnoreCase("404") && check[0]) {
                    check[1] = true;
                    Op2 oP = new Op2(address, ensamblador);//se genera dentro de la clase
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }
            /////////////
            if (jComboBox1.getSelectedIndex() == 3) {
                System.out.println("Se seleccionó la opción 3");
                if (!address.equalsIgnoreCase("404") && check[1]) {
                    check[2] = true;
                    ensamblador.crearMatrizTraslapes();
                    ensamblador.imprimirMatrizTraslapes();
                    Op3 oP = new Op3();

                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }
            /////////////
            if (jComboBox1.getSelectedIndex() == 4) {
                System.out.println("Se seleccionó la opción 4");
                if (!address.equalsIgnoreCase("404") && check[2]) {
                    check[3] = true;
                    ensamblador.ensambla(5);
                    Op4 oP = new Op4();

                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

            //////////
            if (jComboBox1.getSelectedIndex() == 5) {
                System.out.println("Se seleccionó la opción 5");

                int opcion = JOptionPane.showOptionDialog(null, "¿Deseas Guardar los fragmentos en un archivo nuevo?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sí", "No"}, "Sí");

                if (opcion == JOptionPane.YES_OPTION) {
                    FileGetAddress f = new FileGetAddress();
                    //f.fileAddress()
                    ensamblador.guardaEnsambladoEnArchivo(f.fileAddress());
                } else if (opcion == JOptionPane.NO_OPTION) {
                    System.err.println(address);
                    ensamblador.guardaEnsambladoEnArchivo(address);
                }
                if (!address.equalsIgnoreCase("404") && check[3]) {
                    check[3] = true;
//                    ensamblador.guardaEnsambladoEnArchivo(address);
                    Op5 oP = new Op5();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

            /////////////
            if (jComboBox1.getSelectedIndex() == 6) {
                System.out.println("Se seleccionó la opción 6");
                if (!address.equalsIgnoreCase("404") && check[3]) {

                    String hileraOriginal = ensamblador.hileraOriginalDesdeArchivo(address);
                   
                    double similitud = ensamblador.calculaSimilitud(hileraOriginal);
                    System.err.println(similitud);
                    Op6 oP = new Op6(String.valueOf(similitud));
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }
            /////////////
            if (jComboBox1.getSelectedIndex() == 7) {
                System.out.println("Se seleccionó la opción 7");
                if (!address.equalsIgnoreCase("404") && check[3]) {
                    ensamblador.listarFragmentos();
                    String data = ensamblador.getDataListar();
                    Op7 oP = new Op7(data);
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

            /////////////
            if (jComboBox1.getSelectedIndex() == 8) {
                System.out.println("Se seleccionó la opción 8");
                if (!address.equalsIgnoreCase("404") && check[3]) {
                    ensamblador.ordenarAlfabetico();
                    Op8 oP = new Op8();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (Scanner scanner = new Scanner(System.in)) {
            System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out), true, "UTF-8"));
            /////////////
            if (jComboBox1.getSelectedIndex() == 9) {
                System.out.println("Se seleccionó la opción 9");
                if (!address.equalsIgnoreCase("404") && check[3]) {
                    int longitudMinima = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la longitud mínima:"));
                    ensamblador.filtrarPorLongitud(longitudMinima);
                    Op9 oP = new Op9();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

            /////////////
            if (jComboBox1.getSelectedIndex() == 10) {
                System.out.println("Se seleccionó la opción 10");
                if (!address.equalsIgnoreCase("404") && check[3]) {

                    ensamblador.buscarPorPalabraClave(JOptionPane.showInputDialog("Ingrese la palabra clave: "));

                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }

            /////////////
            if (jComboBox1.getSelectedIndex() == 11) {
                System.out.println("Se seleccionó la opción 11");
                if (!address.equalsIgnoreCase("404") && check[3]) {
                    ensamblador.generarGrafoConexoMinimo();
                    Op10 oP = new Op10();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();

                } else {
                    Op404 oP = new Op404();
                    jPanel_Menu.removeAll();
                    oP.setSize(810, 540);
                    oP.setLocation(0, 0);
                    jPanel_Menu.add(oP, BorderLayout.CENTER);
                    jPanel_Menu.revalidate();
                    jPanel_Menu.repaint();
                }

            }
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void derechos() {
        // Obtener año actual
        int anioActual = java.time.Year.now().getValue();

        // Mensaje de derechos reservados
        String mensajePieDeAplicacion = "© " + anioActual + " Todos los derechos reservados.";
        jlabelDerechos.setText(mensajePieDeAplicacion);
    }

    public void iniciar(String palabra, String palabraLabel) {
        jTextArea1.setText("");
        index = 0;
        jLabel4.setText(""); // Limpia el texto anterior en el JLabel

        Timer timer = new Timer(100, new ActionListener() {
            String data = "";

            @Override
            public void actionPerformed(ActionEvent e) {
                if (index >= palabra.length()) {
                    ((Timer) e.getSource()).stop();
                    jLabel4.setText("\\\\(^_^)/");

                } else {
                    if (index < palabraLabel.length()) {
                        data += Character.toString(palabraLabel.charAt(index));
                        jLabel4.setText(data);
                    } else if (data.length() > 0) {
                        data = data.substring(1);
                        jLabel4.setText(data);
                    }
                    jTextArea1.append(Character.toString(palabra.charAt(index)));
                    index++;
                }
            }
        });

        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlabelDerechos;
    private javax.swing.JLabel jlabelDerechos1;
    private javax.swing.JLabel titu1;
    private javax.swing.JLabel titu2;
    private javax.swing.JLabel titu3;
    private javax.swing.JLabel titu8;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return jlabelDerechos;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jlabelDerechos = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel_Menu() {
        return jPanel_Menu;
    }

    public void setjPanel_Menu(JPanel jPanel4) {
        this.jPanel_Menu = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getJlabelDerechos() {
        return jlabelDerechos;
    }

    public void setJlabelDerechos(JLabel jlabelDerechos) {
        this.jlabelDerechos = jlabelDerechos;
    }

    public JLabel getTitu1() {
        return titu1;
    }

    public void setTitu1(JLabel titu1) {
        this.titu1 = titu1;
    }

}
