/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.opciones;

import Domain.EnsambladorDeFragmentosPrueba;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

public final class Op2 extends javax.swing.JPanel {

    EnsambladorDeFragmentosPrueba ensamblador;
    String address;

    public Op2(String address, EnsambladorDeFragmentosPrueba ensamblador) {
        this.ensamblador = ensamblador;
        this.address = address;
        initComponents();
        titu6.setVisible(false);
        titu7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titu7 = new javax.swing.JLabel();
        titu6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        titu8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu7.setBackground(new java.awt.Color(0, 102, 102));
        titu7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titu7.setForeground(new java.awt.Color(0, 0, 0));
        titu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu7.setText("exitosamente.");
        titu7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(titu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        titu6.setBackground(new java.awt.Color(0, 102, 102));
        titu6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titu6.setForeground(new java.awt.Color(0, 0, 0));
        titu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu6.setText("Fragmentos generados ");
        titu6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(titu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 170, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Numero de Fragmentos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 50, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Longitud");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 50, 30));

        titu8.setBackground(new java.awt.Color(0, 102, 102));
        titu8.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 70)); // NOI18N
        titu8.setForeground(new java.awt.Color(0, 0, 0));
        titu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu8.setText("Generar fragmentos");
        titu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(titu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 660, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (Integer.parseInt(jTextField1.getText()) > 0 && Integer.parseInt(jTextField1.getText()) > 0
                || !jTextField1.getText().equals(null) && !jTextField2.getText().equals(null)) {
            jButton1.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            ensamblador.generaFragmentosAleatoriosDeArchivo(address,
                    Integer.parseInt(getjTextField1().getText()),
                    Integer.parseInt(getjTextField2().getText()));
            System.out.println("Fragmentos generados exitosamente.");
            titu6.setVisible(true);
            titu7.setVisible(true);
        } else {
            jTextField1.setText("Error");
            jTextField2.setText("Error");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public void setjTextField2(JTextField jTextField2) {
        this.jTextField2 = jTextField2;
    }

    public JLabel getTitu6() {
        return titu6;
    }

    public void setTitu6(JLabel titu6) {
        this.titu6 = titu6;
    }

    public JLabel getTitu7() {
        return titu7;
    }

    public void setTitu7(JLabel titu7) {
        this.titu7 = titu7;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel titu6;
    private javax.swing.JLabel titu7;
    private javax.swing.JLabel titu8;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
