/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.opciones;

public final class Op404 extends javax.swing.JPanel {

    public Op404() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titu8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu8.setBackground(new java.awt.Color(255, 0, 0));
        titu8.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 100)); // NOI18N
        titu8.setForeground(new java.awt.Color(0, 0, 0));
        titu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu8.setText("ERROR 404");
        titu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(titu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 630, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titu8;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
