/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.opciones;

public final class Op6 extends javax.swing.JPanel {

    public Op6(String similitud) {
        initComponents();
        titu7.setText(similitud + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titu7 = new javax.swing.JLabel();
        titu6 = new javax.swing.JLabel();
        titu8 = new javax.swing.JLabel();
        titu9 = new javax.swing.JLabel();
        titu10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu7.setBackground(new java.awt.Color(0, 102, 102));
        titu7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titu7.setForeground(new java.awt.Color(0, 0, 0));
        titu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(titu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 770, 80));

        titu6.setBackground(new java.awt.Color(0, 102, 102));
        titu6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titu6.setForeground(new java.awt.Color(0, 0, 0));
        titu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu6.setText("La similitud entre la hilera  ");
        titu6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(titu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        titu8.setBackground(new java.awt.Color(0, 102, 102));
        titu8.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 65)); // NOI18N
        titu8.setForeground(new java.awt.Color(0, 0, 0));
        titu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu8.setText("Guardar Fragmentos");
        titu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(titu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 90));

        titu9.setBackground(new java.awt.Color(0, 102, 102));
        titu9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titu9.setForeground(new java.awt.Color(0, 0, 0));
        titu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu9.setText("original y la hilera ");
        titu9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(titu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        titu10.setBackground(new java.awt.Color(0, 102, 102));
        titu10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titu10.setForeground(new java.awt.Color(0, 0, 0));
        titu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titu10.setText("ensamblada es:");
        titu10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(titu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 370, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titu10;
    private javax.swing.JLabel titu6;
    private javax.swing.JLabel titu7;
    private javax.swing.JLabel titu8;
    private javax.swing.JLabel titu9;
    // End of variables declaration//GEN-END:variables

//encapsulamiento
}
